CREATE SCHEMA deepreadingsdb;
ALTER TABLE deepreadingsdb.ANNOTATIONS ADD CONSTRAINT CK_ANNOTATION_TYPE CHECK (TYPE IN ('HIGHLIGHT', 'STRIKETHROUGH', 'TAG'));
INSERT INTO deepreadingsdb.ROLES (ID, NAME) VALUES(0, 'ROLE_ADMIN');
INSERT INTO deepreadingsdb.ROLES (ID, NAME) VALUES(1, 'ROLE_ADMIN_CONCEPT');
INSERT INTO deepreadingsdb.ROLES (ID, NAME) VALUES(2, 'ROLE_ADMIN_DOCUMENT');
INSERT INTO deepreadingsdb.ROLES (ID, NAME) VALUES(3, 'ROLE_READER');


